"""Shared foundations: agent events, the permission gate, notifications, and the
scratchpad directory.

Message and event *types* live in :mod:`vtx.protocol` and tracing lives in
:mod:`vtx.telemetry`; both are leaves that this package depends on.
"""

from .events import (
    AgentEndEvent,
    AgentStartEvent,
    AskUserEvent,
    BackgroundTaskCompletedEvent,
    CompactionEndEvent,
    CompactionProgressEvent,
    CompactionStartEvent,
    ErrorEvent,
    HostNoticeEvent,
    InterruptedEvent,
    RetryEvent,
    SessionEndEvent,
    SessionStartEvent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    ToolApprovalEvent,
    ToolArgsDeltaEvent,
    ToolArgsTokenUpdateEvent,
    ToolEndEvent,
    ToolOutputDeltaEvent,
    ToolResultEvent,
    ToolStartEvent,
    TurnEndEvent,
    TurnStartEvent,
    WarningEvent,
)
from .notify import NotificationEvent, notify
from .permissions import (
    ApprovalResponse,
    AskUserAnswer,
    AskUserOption,
    AskUserQuestion,
    AskUserResponse,
    PermissionDecision,
    _is_safe_bash_command,
    check_permission,
)
from .scratchpad import get_scratchpad_dir, init_scratchpad, is_scratchpad_path

__all__ = [
    "AgentEndEvent",
    "AgentStartEvent",
    "ApprovalResponse",
    "AskUserAnswer",
    "AskUserEvent",
    "AskUserOption",
    "AskUserQuestion",
    "AskUserResponse",
    "BackgroundTaskCompletedEvent",
    "CompactionEndEvent",
    "CompactionProgressEvent",
    "CompactionStartEvent",
    "ErrorEvent",
    "HostNoticeEvent",
    "InterruptedEvent",
    "NotificationEvent",
    "PermissionDecision",
    "RetryEvent",
    "SessionEndEvent",
    "SessionStartEvent",
    "TextDeltaEvent",
    "TextEndEvent",
    "TextStartEvent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ThinkingStartEvent",
    "ToolApprovalEvent",
    "ToolArgsDeltaEvent",
    "ToolArgsTokenUpdateEvent",
    "ToolEndEvent",
    "ToolOutputDeltaEvent",
    "ToolResultEvent",
    "ToolStartEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "WarningEvent",
    "_is_safe_bash_command",
    "check_permission",
    "get_scratchpad_dir",
    "init_scratchpad",
    "is_scratchpad_path",
    "notify",
]
