from vtx.ai.agent.context.skills import register_skills_package

from . import tools as _tools  # noqa: F401
from .config import (
    AVAILABLE_BINARIES,
    CONFIG_DIR_NAME,
    CURRENT_CONFIG_VERSION,
    Config,
    PermissionMode,
    add_recent_model,
    config,
    consume_config_warnings,
    get_agents_dir,
    get_config,
    get_config_dir,
    get_last_selected,
    get_recent_models,
    reload_config,
    reset_config,
    set_colored_tool_badge,
    set_config,
    set_git_context,
    set_last_selected,
    set_model_provider_filter,
    set_notifications_enabled,
    set_permissions_mode,
    set_show_welcome_shortcuts,
    set_theme,
    set_thinking_lines,
    update_available_binaries,
)
from .headless import _exit_code, render_run, resolve_prompt, run_headless
from .version import PACKAGE_NAME, VERSION, format_version

# Register coding agent skills package into harness
register_skills_package("vtx.coding_agent")

__all__ = [
    "AVAILABLE_BINARIES",
    "CONFIG_DIR_NAME",
    "CURRENT_CONFIG_VERSION",
    "PACKAGE_NAME",
    "VERSION",
    "Config",
    "PermissionMode",
    "_exit_code",
    "add_recent_model",
    "config",
    "consume_config_warnings",
    "format_version",
    "get_agents_dir",
    "get_config",
    "get_config_dir",
    "get_last_selected",
    "get_recent_models",
    "reload_config",
    "render_run",
    "reset_config",
    "resolve_prompt",
    "run_headless",
    "set_colored_tool_badge",
    "set_config",
    "set_git_context",
    "set_last_selected",
    "set_model_provider_filter",
    "set_notifications_enabled",
    "set_permissions_mode",
    "set_show_welcome_shortcuts",
    "set_theme",
    "set_thinking_lines",
    "update_available_binaries",
]
